backend:
  name: github
  repo: InsideGH/gatsby-playground
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: games 
    label: Games 
    folder: games
    create: true
    fields: # The fields for each document, usually in front matter
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { label: Lead, name: Lead, widget: string, optional: true, required: false}
      - { label: "Align Content", name: "align", widget: "select", options: ["left", "center", "right"]}